### ISSUE TITLE
disappearing cursor when interacting with flops waveform 

### ISSUE THREAD

**Issue by KNFLD** [ppooll-dev/ppooll#105]
when resizing flops waveform the cursor will disappear and wont re appear until restart. 

OS: Windows 11

**Comment by jpsteccato** [comment]
While I don't think it's possible to really address this issue (seems like a Max on Windows specific issue, not ppooll), I did add a preference to the "prf" menu for disabling the showing/hiding of the mouse in flop.  

If anyone is running into the disappearing mouse issue, they can select "yes" from this menu in ppooll "prf":
<img width="382" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/ac7c6898-6985-4a1e-a2d5-370188ecafa3">
