### ISSUE TITLE
rez@ Not Loading Correctly

### ISSUE THREAD

**Issue by philjulian** [ppooll-dev/ppooll#106]
This is on an M2 Mac with Max 8.5.5 and ppooll 8.5 with the CNMAT packages loaded:

/Applications/Max.app/Contents/Resources/C74/packages/max-mxj/java-classes/
Cannot get_java_vm
Unable to create JVM

The rez@ act passes sound but seems to only be on a single resonant band which can't be changed. I'm not sure what the state of Java is under Ventura 13.4.  Any suggestions as to what I might need to add?

**Comment by chausch** [comment]
ugh, that's an antique patch by me – probably 15 yrs old, not updated in ages.

the mxjs are mostly to do some stuff like liste (de)multiplexing. this could/should all be done different today.  i also had some dev version lying around that animated the bands with random walks and such. too much to do right now.

–– aaaanyway: it works here on mac os 13.4.1. i have java version "17.0.5" 2022-10-18 LTS running here – don't remember where i downloaded it from. i only remember that it was not obvious. 🤔

**Comment by philjulian** [comment]
Thanks, I need to check what Java I have here... I'm not sure what version or even what support Ventura has.  Thanks for the pointers though, much appreciated.

**Comment by chausch** [comment]
try "java -version" in the console!

**Comment by chausch** [comment]
found it in my browser history. i got it here:
https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk#zulu
(not oracle, as one might expect)

**Comment by the-steech** [comment]
i attempted a javascript version of the demultiplexing in the branch "rez-demultiplex-with-javascript".  not familiar with this act so cannot confirm if it's working as it should

**Comment by philjulian** [comment]
> try "java -version" in the console!

Ah, thanks - I have:

java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

Doesn't mean much to me but will have a look at the version you linked, thanks for digging that out

**Comment by philjulian** [comment]
> i attempted a javascript version of the demultiplexing in the branch "rez-demultiplex-with-javascript". not familiar with this act so cannot confirm if it's working as it should

Thanks for trying but no luck with the current java version "1.8.0_371" I have loaded:

Cannot get_java_vm
Unable to create JVM
multislider: Slider 5 Out of Range.
multislider: Slider 8 Out of Range.
multislider: Slider 13 Out of Range.

**Comment by philjulian** [comment]
> found it in my browser history. i got it here: https://www.azul.com/downloads/?os=macos&architecture=arm-64-bit&package=jdk#zulu (not oracle, as one might expect)

Downloading that Java package got the rez@ version in ppooll 8.5 working correctly!  

Thanks again for digging it out, I know *nothing* about Java so have no insight as to the difference between this version and what was already on the Mac (M2, Ventura 13.4)

**Comment by jpsteccato** [comment]
I'd still like to try to implement my .js version of this (in an attempt to minimize the dependency for Java).  Assigning to myself, but may need @chausch input before going wide with this change.

**Comment by jpsteccato** [comment]
i took another look at this today after not looking for a while.  i converted the original .java class into javascript, so no need for Java to use this act anymore :)

**Comment by chausch** [comment]
> i took another look at this today after not looking for a while. i converted the original .java class into javascript, so no need for Java to use this act anymore :)

cool, thanks @jpsteccato
