### ISSUE TITLE
input of large numbers in samplebuffers causes max to freeze

### ISSUE THREAD

**Issue by gregdl** [ppooll-dev/ppooll#113]
It is quite easy for users to accidentally input large numbers into samplebuffers without being able to delete/edit them, and large numbers will cause max to freeze / crash. 

suggestion to either (a) make cmd + click default for number entry in samplebuffers or (b) clamp upper limit of samplebuffers size (i.e. don't allow users to create a 555 hour long buffer)

**Comment by chausch** [comment]
ok i just saw that the slider was limited to 2 seconds already, so i changed the default mode back to slider mode. number should not be capped, as there might be people who still need those hours long buffers 😅
