### ISSUE TITLE
actmaker: creating ll_blues automatically does not work

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#116]

**Comment by jpsteccato** [comment]
i wonder if it's easier to implement something that uses the "Paste From" menu
<img width="559" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/b67ebebb-8f19-4b26-b569-f23c5d2903d6">

**Comment by chausch** [comment]
interesting idea!! 🤔

**Comment by jpsteccato** [comment]
err... for "bpatchers" to work (like ll.blues), we need to create new patcher files with an actual instance of the bpatcher object.  

<img width="456" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/e0bda91f-32a3-4c0f-942f-c343c5132253">

**Comment by chausch** [comment]
hi joe, i implemented a new bpatcher creation function in actmaker_helper.maxhelp – this had already worked years ago but lost functionality in the course of various changes. @klausfilip can you also have a look if this is ok?
there is also a subpatcher titled "build-blue" which appears to be obsolete, but i was reluctant to delete it.

**Comment by jpsteccato** [comment]
very nice!!  working for me :) 

ps: i added a couple other options to the Paste From menu 👀
