### ISSUE TITLE
vst doesn't interface with ppooll audio routing.

### ISSUE THREAD

**Issue by 50NNY1** [ppooll-dev/ppooll#124]
**Summary**
On load of vst@ the following error messages appear in the console:

- folder: Macintosh HD:/Users/sonny/Documents/Max 8/Library/ppooll_presets/vst@P: not a folder
- script disconnect: connection not found
- script disconnect: connection not found

on clicking double clicking the first error message the the error is found in the following subpatch: (the others do not show a point in the patch)

<img width="605" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/31995033/b17135c2-7328-405f-9298-9d8a574f702a">

**My Specs**
Macbook M1
Max 8.5.6
Ppooll 8.6 (latest release)

**Comment by jpsteccato** [comment]
I see these messages as well, they should probably be removed if possible. However I have not had any issues with the functionality of vst@ (despite these messages).

Missing "vst@P" folder would indicate issues with any saved "vst@" preset files.  

I believe the "script connect/disconnect" messages are from the automatic creation of mcs.vst~ (which relies on ll.blues settings).

Just want to check-- is there something not working correctly in this act in terms of functionality?
