### ISSUE TITLE
missing Windows 64bit externals .mxe64

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#128]
the following acts are listed as "not available" for Windows 64 users.  from what I gather these either have 64bit externals or those externals have been replaced:

```
- chaos
- chebyshev@ 
- freeverb@
- spectcomp (act removed from package)
- buffub
```

**Comment by jpsteccato** [comment]
upon further inspection, the actual "check" for acts that are incompatible on Windows 64 lies in `ho_st -> sub -> package_check -> act_menu` in the object [coll no_mxe64].

the list within the coll only lists "freeverb" as incompatible, which has a Win64 that has been tested successfully.  

can we remove "freeverb" from [coll no_mxe64] and all the other acts listed about from the ppooll [info] window?
@klausfilip @chausch 

<img width="718" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/ba69e1fb-c313-46c9-9c04-b4681f809672">

**Comment by klausfilip** [comment]
yes please remove these files from no_mxe64 !
thats quite a time ago

**Comment by jpsteccato** [comment]
thanks klaus, just made the changes !
