### ISSUE TITLE
tetris@ grid_size settings causing crashes

### ISSUE THREAD

**Issue by tobinja1** [ppooll-dev/ppooll#129]
Hey folks!

I just wrote up some wiki documentation on using [tetris@ for beginners](https://github.com/ppooll-dev/ppooll/wiki/tetris@-and-customizing-your-acts) and noticed a consistent issue: the **grid_size** integer isn't clipped at the low end, and anything lower than 2 causes Max to crash by drawing a near-endless amount of preset grids. 

Might we consider putting a lower limit on the numbox? Small issue, I know, but one that proved a bit irksome when using tetris@!

**Comment by klausfilip** [comment]
hi,
i tried to make the crash happen, but failed ;)
the grid-size ll_number has a minimum of 4 here.
¿

**Comment by klausfilip** [comment]
maybe you do have an older version?

**Comment by tobinja1** [comment]
yup, I was absolutely using an older version!! Apologies for this
