### ISSUE TITLE
_act_overview broken

### ISSUE THREAD

**Issue by klausfilip** [ppooll-dev/ppooll#132]
hi joe,
what did you do to _act_overview?
it does not show any acts any more ;(

**Comment by jpsteccato** [comment]
oh no sorry @klausfilip -- i made a change to how [dict act_overview+] is made, it was a small change to act_overview [p filewatch] and most of the changes are in the ll.act_menu_builder.js file in ho_st.

one user on discord reported that they had a duplicate file "ll.act_menu_builder.js" message in Max console-- are you seeing that by change?

**Comment by klausfilip** [comment]
i have only one ll.act_menu_builder.js
in the subpatch of _act_overview i see a disabled patchcord.
but even when i enable it, its not working.
![Screenshot 2023-11-09 at 22 10 23](https://github.com/ppooll-dev/ppooll/assets/37405478/48d5d508-9287-4e91-b189-9682cc19fa44)

**Comment by klausfilip** [comment]
does it work at you ?

**Comment by jpsteccato** [comment]
yes it works for me (and once the other user deleted the duplicate file it was also working for them so it's working on other machines, not just mine)

any errors in console?  do you have a screenshot of the act with the empty rows?

**Comment by klausfilip** [comment]
dict: index out of range for key acts
dict: no dictionary named INmulti, cannot get value
dict: index out of range for key acts::INmulti::usage
dict: no dictionary named control@, cannot get value
dict: index out of range for key acts::control@::usage
dict: no dictionary named gverb@, cannot get value
dict: index out of range for key acts::gverb@::usage
dict: no dictionary named hardplay, cannot get value
dict: index out of range for key acts::hardplay::usage
dict: no dictionary named modul.ator, cannot get value
dict: index out of range for key acts::modul.ator::usage
dict: no dictionary named noize@, cannot get value
dict: index out of range for key acts::noize@::usage
dict: no dictionary named sinsE, cannot get value
dict: index out of range for key acts::sinsE::usage
dict: no dictionary named snap@, cannot get value
dict: index out of range for key acts::snap@::usage
dict: no dictionary named tetris@, cannot get value
dict: index out of range for key acts::tetris@::usage
dict: no dictionary named vbap@, cannot get value
dict: index out of range for key acts::vbap@::usage
dict: no dictionary named xgroove@, cannot get value
dict: index out of range for key acts::xgroove@::usage
dict: no dictionary named pr.spectplay, cannot get value
dict: index out of range for key acts::pr.spectplay::usage
dict: index out of range for key tags
dict: index out of range for key acts

**Comment by klausfilip** [comment]
sorry i have to say, its a bit annoying.

its a patch that costed me many hours of work and now it was maybe the first time i wanted to get some info from it.
i appreciate very very much, if you do updates and bugfixes, but this seems to be broken for me.
still maybe -  i can't handle github very well and was breaking something myself.
but we have to find the bug in the bugfix now ... 
what was the bug in there anyway, i did not react myself on this - not showing acts at what action?
--
i would suggest, that fixes on an act, that is clearly work of somebody, should be "daccorded" with this person first...

sorry again, just clueless
klaus

**Comment by klausfilip** [comment]
oh, i did not want to write zjs bold and in big letters !!

**Comment by jpsteccato** [comment]
sorry klaus-- if you click the dict messages, does it point to the offending object in the patch?  

i made these changes because of an issue where if an act in unshared or community_contributions was marked "never" in usage, the act would not appear in the act_overview at all (because act_overview was using [coll actmenu] to build the act_overview+, which does not list "never" acts).

i did test this thoroughly and was very careful about what changes were made (most of which are in the .js file).  

if you want to try to get on a call, i'd be happy to figure this out together

**Comment by klausfilip** [comment]
where is the connection to ll.act_menu_builder.js ?
..where is it used?

**Comment by klausfilip** [comment]
this is how the patch looks her, with the errors pasted above.
![Screenshot 2023-11-09 at 23 15 46](https://github.com/ppooll-dev/ppooll/assets/37405478/22a6ec04-8c8f-44ea-8f0c-1b9a91d3b28b)

**Comment by jpsteccato** [comment]
ll.act_menu_builder.js (in ho_st) now also builds a js Dict("act_overview++").  what does act_overview++ look like in act_overview subpatch in [p filewatch]?

**Comment by klausfilip** [comment]
its emty

in ho_st i can't find act_overview++

**Comment by klausfilip** [comment]
are we using the same branch main ??

**Comment by jpsteccato** [comment]
I think we are both on the latest?  the act_overview++ is only referenced in the ll.act_menu_builder.js in ho_st

**Comment by klausfilip** [comment]
in the js i only see "act_overview" but no "act_overview++"

**Comment by klausfilip** [comment]
thats the js here::

/*
	ll.act_menu_builder.js

		on bang, build the act menu and set coll objects
*/
autowatch = 1
inlets = 1;
outlets = 5;

var console = { log: function(args){ post(args); post(); } }

var MAIN = 			"Package:/ppooll/patchers/ppooll.acts"
var CONTRIBUTIONS = "Package:/ppooll_contributions/patchers/ppooll.acts"
var IGNORE_LIST = ""
var count = 0

// for _act_overview
var dict_act_overview_plus = new Dict("act_overview++")
dict_act_overview_plus.import_json("act_overview.json")

// get file extension, return [name_only, ext]
function get_extension(filename){
	return[
		filename.substring(0, filename.lastIndexOf(".")),
		filename.substring(filename.lastIndexOf(".")+1),
	]
}

function sortObjects(originalObject){

	// Step 1: Get the keys and sort them
	var keys = [];
	for (var key in originalObject) {
	  if (originalObject.hasOwnProperty(key)) {
	    keys.push(key);
	  }
	}
	keys.sort();

	// Step 2: Create a new object with sorted keys
	var sortedObject = {};
	for (var i = 0; i < keys.length; i++) {
	  var currentKey = keys[i];
	  sortedObject[currentKey] = originalObject[currentKey];
	}
	return sortedObject
}

// outlet shortcut to umenu
function append(name){
	outlet(0, ["append",name])
	outlet(2, ['store',name,count])
	count++;
}

function store(name){
	outlet(1, ['store',name,1])
}

function watch_folder(id,folder){
	outlet(3, [id, folder])
}


// get file extension, return [name_only, ext]
function load_acts_from_folder(folder, desc){
	var f = new Folder(folder)
	f.typelist = ['JSON']
	//post("\n", "folder",folder,f,"\n");
	while (!f.end) {
		var file_ext = get_extension(f.filename)
		//post(f.filename);
		if(file_ext[1] === 'maxpat'){
			if(IGNORE_LIST.indexOf(","+file_ext[0]+",") === -1){
				append(file_ext[0])
			}
			if(file_ext[0] !== '_act_overview'){
				store(file_ext[0])
			}

			if(desc){
				dict_act_overview_plus.setparse("acts::" + file_ext[0], JSON.stringify({
					"description": desc,
					"authors": "",
					"tags": ''
				}))
			}
		}
		f.next()
	}
}	


function bang(){
	outlet(0, 'clear')
	outlet(1, 'clear')
	outlet(2, 'clear')

	count = 0;

	var dict_preferences = new Dict("ppooll-preferences")

	var UNSHARED = dict_preferences.get('file_paths::unshared_acts')
	IGNORE_LIST = ","+dict_preferences.get('act_usage::never_used_acts') + ",_act_overview,"

	// MAIN
	append("(__acts__)")
	append("_act_overview")
	store("_act_overview")

	load_acts_from_folder(MAIN, false)
	watch_folder(1,MAIN)

	// CONTRIBUTIONS
	append("-")
	append("(community contributions)")
	load_acts_from_folder(CONTRIBUTIONS, "(community contributions)")
	watch_folder(2,CONTRIBUTIONS)

	// UNSHARED
	append("-")
	append("--unshared_acts--")
	if(UNSHARED !== ""){
		load_acts_from_folder(UNSHARED, "--unshared_acts--")
		watch_folder(3,UNSHARED)
	}

	var jsonOverviewPlus = JSON.parse(dict_act_overview_plus.stringify())
	var newActs = sortObjects(jsonOverviewPlus.acts)
	dict_act_overview_plus.setparse("acts", JSON.stringify(newActs))

	outlet(4, 'bang');
}

**Comment by jpsteccato** [comment]
it's referenced towards the top, this line:
```var dict_act_overview_plus = new Dict("act_overview++")```

**Comment by klausfilip** [comment]
ah ja,
i found it now,
but still in the patch _act_overview this dict is empty..
i relaunch max, for safety...

**Comment by klausfilip** [comment]
pffff, yes !!!!

**Comment by klausfilip** [comment]
obviously all this happened, becuase ho_st was open here all the time, when switching branches.
see, thats me not understanding, what github dies on my machine ;))

sorry for all this !!

**Comment by jpsteccato** [comment]
phewwww 😅 i was gonna say, when I "pull" changes I usually need to refresh Max/ppooll altogether

**Comment by klausfilip** [comment]
yes, and thats very logic also - haha
sorry again for being irritated here.

**Comment by klausfilip** [comment]
have a nice smooth evening, please

**Comment by jpsteccato** [comment]
you were totally fine!  yes, you too :)
