### ISSUE TITLE
buffer_host create buffer size larger than 2 seconds?

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#136]
i'd like to propose 2 changes to the "size in ms" slider in the "samplebuffers" window (for creating an empty buffer):

- increasing the "slider-max"value from 2secs -> 2mins (considering the slider label indicates minutes-seconds-ms)
- setting a "max" value of 2 hours (7,200,000 ms)

any thoughts @klausfilip @chausch ?

<img width="541" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/3166a911-806f-48a1-bf29-a8dbe8ea760e">

**Comment by chausch** [comment]
not a problem with that personally, but this might lead to more user reported issues such as #113

**Comment by klausfilip** [comment]
yes sure, why not. 
the 2 seconds must derive from times, when there were just a few MB and no virtual RAM ...

**Comment by jpsteccato** [comment]
thank you both :)   from my testing it seems to take 2 hour buffers well and has no effect on performance, ill make the adjustment
