### ISSUE TITLE
flop buffer names -- conflict with jasch package & unable to parse?

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#137]
some strange issues for one discord user with flop

- conflict with jasch package -- if this is required by ppooll from Max Package Manager, can we just use those versions and delete the ones in ppooll repo?

- unable to parse buffer?

![image](https://github.com/ppooll-dev/ppooll/assets/37079335/2d04f99e-0ea1-4616-b2c0-f58b13ddbc48)

**Comment by chausch** [comment]
i'd say delete the included version and make jasch a required dependency.

**Comment by klausfilip** [comment]
i made a subpatch in flop to generate these playback-buffers there.
so ho_st is no more loading these.
