### ISSUE TITLE
snap@ initial state, Max Console messages, audio turning on-off when switching presets

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#141]
getting a couple reports of unsuspected behavior with snap@

- some users reporting audio turning on/off when switching snap presets
- Max Console messages "sel_acts freeverb@ ho_st@..."
- the initial state looks like a different tetris layout?

<img width="281" alt="image" src="https://github.com/ppooll-dev/ppooll/assets/37079335/d01bc1b0-bd4b-40ae-871f-c8c74cb2b797">

klaus could you look when you have a second?

**Comment by klausfilip** [comment]
i recommend testing snap@ with the "factory" environment ducks.

**Comment by jpsteccato** [comment]
this is all good klaus, thanks :)
