### ISSUE TITLE
control@ -- overflow of rows in "routing" window on Max 8.6.0

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#143]
doing some testing using Max 8.6.0 the last few days and just now ran into my first issue.

when I send a modulator value to control using "control@1::val1", it makes hundreds of rows in the "routing" window.  sometimes this causes Max to crash, sometimes it just becomes extremely sluggish

this also happens with signaltocontrol, it *might* be something to do with the ll_fastforward object?  maybe some update on the Max side of things is causing something to output too many messages?

<img width="768" alt="Screenshot 2024-01-21 at 8 26 37 PM" src="https://github.com/ppooll-dev/ppooll/assets/37079335/c20cc18e-4af4-4187-bbf7-adb94423c3f2">

**Comment by jpsteccato** [comment]
I think i figured out a fix for this, I'm gonna push the change to the "dev-joe" branch if you have a chance to check it out

in the control@_sub -> [p new] subpatch, I changed the [ll.p input_name] to ll.pp -- will this work ok?

<img width="1137" alt="Screenshot 2024-01-22 at 8 39 23 PM" src="https://github.com/ppooll-dev/ppooll/assets/37079335/48bdbc4c-cedb-4b5b-be6e-000550f62b95">

**Comment by klausfilip** [comment]
this is a confirmed bug after an update to the pattr system, see:
https://cycling74.com/forums/max-860-pattrstorage-bug?replyPage=1#reply-65b11d7266c41e0013be509e

**Comment by klausfilip** [comment]
i am afraid, there will be other issues appearing in ppooll caused by this bug,
and it is not easy to find a workraound.
putting a deferlow, as jeremy bernstein suggests, maybe in all relevant abstractions (ll.p, etc.) would break the message orders...
actually i would send out a warning for updating to max 8.6.0 ??
what do you think?

**Comment by klausfilip** [comment]
sometimes issues like this get fixed quickly, especially after a new major upgrade, there were often quick follow up releases...

**Comment by jpsteccato** [comment]
oh that's a great find klaus, this would mean ll.pp is really only a band-aid fix in this one case... waiting for a fix from cycling makes the most sense.  

after making that fix, 8.6.0 has seemed fine to me in terms of sending/receiving parameters, but maybe there is something else going wrong i'm not aware of (so yes, i warning or "not compatible with 8.6.0" makes sense)

**Comment by jpsteccato** [comment]
this is fixed after Max 8.6.1, closing :)
