### ISSUE TITLE
new beast audio input

### ISSUE THREAD

**Issue by gregdl** [ppooll-dev/ppooll#152]
On new ppooll (8.6.0.240524.1)
In the prior beast act you could route audio via "in" and use beast as a looper. 
The newest version doesn't seem to allow this (I can route audio into it "rec_vol.1" but it doesn't seem to loop)?

**Comment by chausch** [comment]
@nnooiidd

**Comment by chausch** [comment]
ah, that was an easy fix. i added that back from the previous version.
