### ISSUE TITLE
gverb is not routed to host automatically

### ISSUE THREAD

**Issue by smakhtin** [ppooll-dev/ppooll#154]
![image](https://github.com/user-attachments/assets/ed73835f-d31b-4bc0-898a-682b991f6ba5)
In such setup, I need to route gverb explicitly to host to get any sound. With xfilter at the end of the chain it all works with no/no routing.

**Comment by smakhtin** [comment]
Looks like mix shouldn't be all the way up, then it works.

**Comment by smakhtin** [comment]
Sill, gverb is behaving weird, when you need to move it to 2 channel mode, otherwise there is no sound. When you put it back to 1 channel mode it works.

**Comment by chausch** [comment]
i just checked and can't find any odd behaviour. can you specify more clearly what is and is not working?
also: are you using the current ppooll version?

**Comment by chausch** [comment]
btw. just so you know: gverb relies on the nw.gverb~ external which is mono input only. if you switch channel processing mode to more than 1 they will all be mixed back to one channel anyway.

**Comment by smakhtin** [comment]
@chausch Can't reproduce the bug with gverb. Not sure why gverb is mono, when I enable the processing channel count to 2 I get the stereo signal out, but it's produced out of 1 mono signal. Is this correct?

![image](https://github.com/user-attachments/assets/24f6ad43-8c91-4676-84d2-dd43abcbbb33)

**Comment by chausch** [comment]
yes, unfortunately that's how the gverb external is designed, which we are using here.
