### ISSUE TITLE
Acts Routing Problem 

### ISSUE THREAD

**Issue by rsabbatella** [ppooll-dev/ppooll#156]
Hi all, I am writing here to report a problem with the routing of acts. Basically, when I send out audio from one act in stereo and enter another act by putting in.0 in the blue section of the starting act, in the destination act the audio only comes in the first channel, the left one. If I change by putting in.1 it stays on the left while if I put in.2 it totally disappears. 

I am using the latest vesion of max and ppooll and my operating system is sonoma 14.5 
i put some screenshots attached of the problem 

<img width="381" alt="Screenshot 2024-08-08 alle 11 45 38" src="https://github.com/user-attachments/assets/1e0093b3-6aac-4f30-938b-63e882c285d8">
<img width="411" alt="Screenshot 2024-08-08 alle 11 45 50" src="https://github.com/user-attachments/assets/62f1db44-edf3-43e6-ac08-1b9d3ada1dfc">
<img width="469" alt="Screenshot 2024-08-08 alle 11 45 59" src="https://github.com/user-attachments/assets/5155d45d-77ad-4603-a88c-0fc00aa5c8f2">
<img width="426" alt="Screenshot 2024-08-08 alle 11 46 09" src="https://github.com/user-attachments/assets/897498d1-3bb8-4171-9ed4-6b0764961361">

**Comment by chausch** [comment]
hi there, in case of chebyshev@ there was clearly a bug in chebyshev@ itself. i just uploaded a fix. 
for ll_inputmix we'll have to investigate further …

**Comment by rsabbatella** [comment]
Hi, and thanks for the quick reply, I have re-downloaded and replaced the whole folder in max packages but the problem seems to be as before

**Comment by chausch** [comment]
did you re-download via code > download zip? the changes are not yet in a new released package!

**Comment by rsabbatella** [comment]
first tried replacing the acts that were changed and then, since the problem had not gone away I re-downloaded and replaced the whole .zip folder

**Comment by chausch** [comment]
ok maybe some clarifications: in.0 is always a mono input.  sending stereo channels to in.0 makes little sense.

anyway look at these screenshots replicating what you described:
<img width="327" alt="Bildschirmfoto 2024-08-08 um 22 01 05" src="https://github.com/user-attachments/assets/ac921af6-add9-4332-b8f7-538326549ccb">
<img width="324" alt="Bildschirmfoto 2024-08-08 um 22 01 12" src="https://github.com/user-attachments/assets/f390d2b4-b844-4278-9b48-d80fd3f7a6b4">
<img width="320" alt="Bildschirmfoto 2024-08-08 um 22 01 19" src="https://github.com/user-attachments/assets/bffded00-8720-4978-9cc8-eb28c68c5a9c">

**Comment by rsabbatella** [comment]
strange, this doesn't happen to me by replicating the same configuration, with sinus having as output chebyshev & in 0 in the arrival module the audio appears only in the left channel and not in both as happens in your examples. In any case, if in.0 is considered as a mono input, how do I get stereo into an act, in this case  the chebysh?

<img width="382" alt="Screenshot 2024-08-08 alle 23 27 14" src="https://github.com/user-attachments/assets/b4158dd8-85d5-4b45-8ac3-fb947d5a9b5b">
