### ISSUE TITLE
buffub forwarding audio even when mix slider is fully off

### ISSUE THREAD

**Issue by jpsteccato** [ppooll-dev/ppooll#160]
when i have the mix slider all the way down in buffub, there is still audio being sent to ll.blues

<img width="255" alt="Screenshot 2024-12-17 at 10 37 48 AM" src="https://github.com/user-attachments/assets/9a3aa660-f51e-4992-8db3-6c28a65c5cd6" />

in the ll.blues abstraction, I can see the audio is coming from the ll.in_mix abstraction

<img width="269" alt="Screenshot 2024-12-17 at 10 41 23 AM" src="https://github.com/user-attachments/assets/49058941-61ad-458f-a9a3-a00fd3481a9a" />

**Comment by chausch** [comment]
weird, i can't reproduce that 🤔

**Comment by klausfilip** [comment]
hmm, 
buffub has no in_mix in the ll.blues interface.
i am not sure now, if then the ll.in_mix in the subpatcher also should NOT be there.
i will look into it

**Comment by klausfilip** [comment]
yes, 
ll.in_mix should NOT be there in the subpatch of the default ll.blues.maxpat !!
(obviously i saved it wrongly at some recent update, that i sent to leli ??)
...
i cannot upload savely to github at the moment, so one of you, who has the current version, please change this...
its attached here (saved in max9..??
[ll.blues.maxpat.zip](https://github.com/user-attachments/files/18187315/ll.blues.maxpat.zip)
)

**Comment by klausfilip** [comment]
pffff, the default routing to ho_st broke here

**Comment by klausfilip** [comment]
[ll.blues.maxpat.zip](https://github.com/user-attachments/files/18187978/ll.blues.maxpat.zip)
try this..

**Comment by jpsteccato** [comment]
this is working for me!  thank u both :)
