### ISSUE TITLE
active settings not stored with the patch

### ISSUE THREAD

**Issue by klausfilip** [ppooll-dev/ppooll#22]

**Comment by klausfilip** [comment]
solved!

**Comment by the-steech** [comment]
@klausfilip this still isnt working for me when I try to uncheck "NumOfInputs" param in matriarch@, save the .maxpat, and reload via host

**Comment by the-steech** [comment]
@klausfilip this still isnt working for me when I try to uncheck "NumOfInputs" param in matriarch@, save the .maxpat, and reload via host

**Comment by the-steech** [comment]
yes, i'm using the latest version from github, here's a video of what im trying to do, maybe i'm doing this wrong?  https://streamable.com/mssy1h

**Comment by klausfilip** [comment]
thats very amazing, because here i works correctly.

hmm, do you maybe have a preset-menu selected in your matriarch@ ?
pls open the clientwindow and scroll for pres_menu, whats your data there??

if so select the _ (very last entry) in matriarch@ pres-menu and save it again

**Comment by the-steech** [comment]
sorry klaus :( I tried as you suggested, and i still can't get the disabled ones to stick.  

under pres_menu, it's an underscore "_"

**Comment by the-steech** [comment]
resolved thanks to klaus, turns out i was using a version of host from my trash can
