### ISSUE TITLE
todo: fix pr.spectfreeze

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#28]
mc-ify in the process if easily doable …

**Comment by elinsound** [comment]
this works fine for me on ppooll 8.0

maybe it just needs MC from here?

[pr.spectfreeze.maxpat.zip](https://github.com/ppooll-dev/ppooll/files/10449378/pr.spectfreeze.maxpat.zip)

**Comment by klausfilip** [comment]
fixed it, but it is still mono

**Comment by chausch** [comment]
> fixed it, but it is still mono

ok thanks, i can do the mc-conversion!

**Comment by chausch** [comment]
mc update done 😊
also corrected credits for fft-code, which comes from Jean-François Charles' spectral tutorials.
