### ISSUE TITLE
xgroove external is broken / no longer maintained – create replacement

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#31]
@jpsteccato you're already nearly there …
😊

**Comment by klausfilip** [comment]
joe, can you by any means imagine to call your no.groove@ xgroove@ ? ;)

**Comment by the-steech** [comment]
i am open to it, but i'm worried about how different the patch is and the parameters.  i wouldn't want users to load old environments with xgroove with all mangled preset param values.  i was working on the gen~ object last night and would like to get it as close as possible to original thomas grill xgroove~ (it's getting very close! :))) )

klaus, is there any reason you want to keep the xgroove@ name?

**Comment by klausfilip** [comment]
..yes, same issue that peoples environment should work.
if there are some other parameters, the environment still sets all the rest.
if there is a new name to an act, the environment stops loading.

**Comment by the-steech** [comment]
ahhh i see, i thought we would include old xgroove@ (for legacy) and new no.groove@ in ppooll acts

**Comment by the-steech** [comment]
this is getting very close... still have conflicting thoughts on whether this should replace xgroove@ or be it's own act.  

when the gen~ is finished, I'm going to package it all nicely as a max external package, with source code available in my github.  figure other max programmers can use and download this as well for non-ppooll projects

**Comment by klausfilip** [comment]
ok... your motivation and plot for your gen~ was xgroove~. you can distribute your gen~ any time in any name. your patch is also using the template of the original (my) xgroove@ patch (ll.wf, ll_mcwaveform,etc). you did a fantastic improovment, both with your gen-code and with the looping envelope. i see it as a good example of collaboration on one theme: xgroove@ (originally designed by thomas grill) ...

**Comment by klausfilip** [comment]
onother point: if you push it with a new name, the xgroove@ is totally redundant, and we need to delete it.

**Comment by the-steech** [comment]
gen is implemented and working :)
