### ISSUE TITLE
cryptic error message related to preset json files

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#32]
dict: file not found: notfound …/Max 8/Library/ppooll_presets/****/_.json
happens with apparently every opened act.
does not seem to hinder the act's functionality …
🤔

**Comment by chausch** [comment]
ho_st/ho_st-subpatches/presetHanlder/read/active_hack/check_clientstate
seems to be the origin of the error.
@klausfilip can you have a look at that?

**Comment by klausfilip** [comment]
fixed..
