### ISSUE TITLE
clean up (presumably redundant work-)files

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#35]
@klausfilip are these ready to be deleted?
- [ ] tetrishelp copy.js
- [ ] nblue copy.js
- [ ] nblue copy 3.js
- [ ] nblue copy 2.js
- [ ] ll.blues copy.maxpat
- [ ] ll.sa copy.maxpat
- [ ] ll.r~ copy.maxpat
- [ ] ll.ra_default copy.maxpat
- [ ] ll.ra copy.maxpat
- [ ] ll.multibutton copy.maxhelp
- [ ] ll_number copy.mxo

**Comment by klausfilip** [comment]
claro que si
