### ISSUE TITLE
matriarch@: js: can't find file createGains.js

### ISSUE THREAD

**Issue by klausfilip** [ppooll-dev/ppooll#42]
get this error, when loading matriarch@:

js: can't find file createGains.js

**Comment by klausfilip** [comment]
and btw, matrix@ can do stereo as well, just pushed a minor bug there..

**Comment by the-steech** [comment]
that file won't effect the device functionality (it was just automation for creating all the knobs are coordinates).  it will be removed when I push the latest matriarch (to-do for me!) thanks klaus
