### ISSUE TITLE
ll.blues: chans out mono mode

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#44]
ll.blues seems to force-mix output to stereo at the minimum, even if i 1 channel is specified as output in "chans" variable.

**Comment by Pogslammer** [comment]
I've been having this issue (sound generators outputting to mono), and after fiddling, if I change the blues output # to 1, it goes stereo, turning it back to 2 will revert to mono (so, sort of the opposite of what you'd want). Just my 2 ¢!

**Comment by klausfilip** [comment]
solved

**Comment by chausch** [comment]
awesome!
