### ISSUE TITLE
ho_st stereo mixdown option behaving (maybe) not as expected

### ISSUE THREAD

**Issue by chausch** [ppooll-dev/ppooll#45]
ho_st stereo mixdown should (imo) eliminiate mc-output and ONLY produce stereo output. else people can use other means to produce an extra stereo mix.

**Comment by chausch** [comment]
what do you think @klausfilip?

**Comment by klausfilip** [comment]
hmm yes, its definitely wrong like it is now. the higher channel-amount is sticky..

**Comment by klausfilip** [comment]
does not work with mc.gate~, does not work with mc.selector~, needs scripting !

**Comment by klausfilip** [comment]
like this ?? @chausch

**Comment by chausch** [comment]
sorry, forgot to give feedback – working great now!! 😊
