### ISSUE TITLE
add back jit.videoplanes

### ISSUE THREAD

**Issue by the-steech** [ppooll-dev/ppooll#49]

**Comment by chausch** [comment]
don't remember this one – was this removed for a reason @klausfilip ?

**Comment by the-steech** [comment]
i added this back to the branch 49-add-back-jitvideoplanes, but was having trouble loading with jit.player

**Comment by chausch** [comment]
i think this should also be in discussions / ideas. as i said i don't remember jit.videoplanes – never used it. @klausfilip ?

**Comment by klausfilip** [comment]
i added them back on the block.
