### ISSUE TITLE
add back INa

### ISSUE THREAD

**Issue by the-steech** [ppooll-dev/ppooll#50]

**Comment by chausch** [comment]
it also doesn't adhere to multichannel standard. -> big thumbs down …

**Comment by klausfilip** [comment]
i did a major update to INmulti. by default it now behaves like INa did. by default it plays stereo to ho_st.
again i would also like to keep INa out. ppooll users should get familiar with def_out and maintain the fear of the mc-architecture ;)

**Comment by the-steech** [comment]
totally agree that it would be ideal to have one act for all this, will check out the update shortly :)

**Comment by the-steech** [comment]
finally got around to checking this out, works great imo.  we'll see what the community thinks, but closing for now !
