### ISSUE TITLE
rec@ in "adoutput" mode, all audio going to chans 1 & 2

### ISSUE THREAD

**Issue by the-steech** [ppooll-dev/ppooll#52]
test by routing audio from any act to host channels 3 & 4, and check monitor in rec@ when set to "adoutput" mode

**Comment by chausch** [comment]
good find, but it's actually not really a bug. adoutput~ accesses the audio driver. when you have 2 hardware outs only 2 chans can be accessed by adoutput~.
test by switching out driver to blackhole!

**Comment by the-steech** [comment]
ahhh of course, my max i/o mappings are all set to outputs 1 & 2, thank you-- closing!
<img width="362" alt="image" src="https://user-images.githubusercontent.com/114934553/212739540-cf771629-5b3f-4a05-82db-5987e9c2f885.png">
