### ISSUE TITLE
INmulti minor issue renaming channels

### ISSUE THREAD

**Issue by the-steech** [ppooll-dev/ppooll#53]
selecting channels 3 & 4 shows channel labels as "i3", "2"
<img width="328" alt="Screen Shot 2023-01-16 at 12 29 14 PM" src="https://user-images.githubusercontent.com/114934553/212736611-9bf6c35c-2911-4b39-bbcf-e5f800e3c49e.png">

**Comment by chausch** [comment]
i think that is actually a bug in ll_number. i just tried to fix it, but ll_number doesn't accept "label" messages with only one integer attached. @klausfilip can you shed some light on that one?

**Comment by chausch** [comment]
nevermind, just fixed it by converting the label to a symbol before sending it to ll_number.

**Comment by chausch** [comment]
actually this is still not resolved

**Comment by chausch** [comment]
now it's fixed – please check!

**Comment by the-steech** [comment]
just confirmed this is fixed-- closing !
