### ISSUE TITLE
Stereo Output Issue with Blues

### ISSUE THREAD

**Issue by Pogslammer** [ppooll-dev/ppooll#58]
I am having an issue with the channel output of numerous acts. Stereo sound generators (i.e., flop@, benjolino@, etc.) open with "2" in the bottom right output count, but will play in mono. Changing the output to "1" will send out stereo audio. Some effects acts (freeverb@ and gverb@ are ones I've tried) don't allow me to change the number to "1", so just stay mono. Wanted to share that, thanks for all the hard work!  

PS- Using a Mac on Catalina, with latest Max and build of ppooll

**Comment by chausch** [comment]
do you use the latest release or the current source code?
in case you use the release please replace it with the current code!

**Comment by Pogslammer** [comment]
Sorry, yes I've been using the latest code

**Comment by the-steech** [comment]
@Pogslammer try this (using benjolino as example)

having "1" in the "input" boxes does mono over the "2" "output" channels
<img width="173" alt="image" src="https://user-images.githubusercontent.com/114934553/213817877-edf8c000-8287-474b-96c0-4516897eff6a.png">

having "2" in the "input" boxes does stereo over the "2" "output" channels
<img width="173" alt="image" src="https://user-images.githubusercontent.com/114934553/213817971-d295d9b0-ac07-4c20-acfd-e55bdbd30cf1.png">

hope this helps :) 

maybe this "input/incoming" box should default to 2?  @klausfilip @chausch

**Comment by the-steech** [comment]
or maybe just update ll.blues state for acts which are stereo...

**Comment by Pogslammer** [comment]
Thanks so much for the response!

Yes, changing the number to "2" on the input did change the acts to stereo. It would make sense to me to default that to "2"; it's a bit counterintuitive for me to think of inputs on acts in which there is no incoming signal. Thanks again, and I apologize for having absolutely no coding ability to contribute to this amazing project!

**Comment by the-steech** [comment]
Of course, glad it's working.  Still wrapping my head around ll.blues.  No need to apologize-- reporting issues/feedback is a contribution :)

**Comment by chausch** [comment]
@Pogslammer @the-steech
actually the left number box is not only input buit also defines amount of dsp voices processing.

so a patch with 1 in - out 2 should create 1 voice (plus corresponding input), doubled up to 2 outputs
2 "in" - 1 out should create 2 voices (plus corresponding inputs), mixed down to 1 output.

(you see, thinking in mc does not only apply to mutiple speakers and output channels but general poplyphony!)

**Comment by chausch** [comment]
iterating over the original question: some acts (like the mentioned freeverb and gverb) are hard-coded for mono or stereo behaviour. meaning that they only accept eg. mono-in/stereo-out or stereo-in/stereo-out our mono-in/out.
that's due to the used externals. there are bpatcher options for ll.blues (visible with tetris) to define mins and max for ins and outs.

in the long run _all_ acts _should_ support mc in ppooll. we are working on this.

reverbs in general are a tricky problem, as they very often deal with either hand-tuned delay lines or cross-channel-feedback. these are things that are difficult to expand …

**Comment by chausch** [comment]
even more info: an ideal ppooll acts does not use externals but exposes the full source code, allowing us to extend it in the future. something to keep in mind when creating acts …

**Comment by chausch** [comment]
we really need better documentation 😅

**Comment by chausch** [comment]
@the-steech to limit in chans you can use "@chans_in min 2 @chans_in max 2" argument for ll.blues

**Comment by chausch** [comment]
@Pogslammer whats the status on this – do you still have a weird behaviour or was the issue based on misinterpretation of the options?

**Comment by Pogslammer** [comment]
@chausch yes, I'm pretty sure it was just misinterpreting the options on my end.

**Comment by chausch** [comment]
great, then i'll close this issue! thanks for the feedback!
