### ISSUE TITLE
Illegal filenames prevent Windows git clone

### ISSUE THREAD

**Issue by burgersmoke** [ppooll-dev/ppooll#69]
I was trying to clone latest from the repo and I got this error:

```
error: invalid path 'patchers/abstractions/filip/ll.pnew?.maxpat'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

I'm not sure if I need to do something different or if there's some other workaround?  Filenames with `?` and several other characters are illegal under Windows.  However, in the .ZIP file download of my ppooll `8.5.1` release and this same file is named this: `ll.pnew_.maxpat`

Could we change the repo filenames for this and others to not have characters which Windows does not allow?  Or is there some other way we can work nicely between OSes?

**Comment by chausch** [comment]
oh!!! 😬 @klausfilip ?

**Comment by chausch** [comment]
ok, according to this 
https://apple.stackexchange.com/questions/147415/find-windows-incompatible-file-folder-names
only 2 files are affected:
`find . -name '*[<>:"/\\|?*]*'`
`./patchers/abstractions/kocyu/keyboard?`
`./patchers/abstractions/filip/ll.pnew?.maxpat`
i can't find any reference in the other files that these are actually used. i'm going to delete them and see if there are problems. we can revert if there are …

**Comment by chausch** [comment]
ok done. keyboard was safe to delete and i just removed the ? from ll.pnew? for testing as there was no other file named that way. could you try cloning again @burgersmoke ?

**Comment by klausfilip** [comment]
thanks cx

**Comment by burgersmoke** [comment]
Fantastic.  I am able to do a `clone` now with no issues.  I wasn't sure if there were any references to these, so thank you @chausch  for checking on that.   I brought this fresh clone into my current Max Packages and all seems to be well.  Thank you for the quick response on this one!
