### ISSUE TITLE
buffer_host weird loading behavior

### ISSUE THREAD

**Issue by the-steech** [ppooll-dev/ppooll#70]
on opening a buffer-related act, sometimes an old version of buffer_host is loaded.  not sure if related to removal of "buffer_host" from ppooll.acts folder.  here's a screenshot which shows the old version which is missing my presets, and the filepath of the loaded buffer_host.maxpat 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/114934553/214633050-b9f507c5-2f7c-4cac-8877-e23cccb93d2e.png">

**Comment by klausfilip** [comment]
aha, can you verify if you have 2 versions in your searchpath?
the desicion of taking buffer_host out of the act-menu was after a chat with a user, who asked, why 2 buffer_haosts are not working correctly...

**Comment by the-steech** [comment]
i haven't been able to find on in my searchpath.  however i have some old files in other places on my computer, i am going to say it is probably those and close this issue :)

**Comment by the-steech** [comment]
sorry to reopen this, but a user in the discord reported a very similar issue.  i've since cleared out all my files, even moved the buffer_host back to the acts folder... but no fix

here are the steps for how recreate this bug:

- open Max 8
- open xgroove@
- buffer_host.maxpat loads from /abstractions, but all buttons are unresponsive, folder presets are missing.  
- it looks like it does load files into the jit.cellblock, but the names are missing.  just the empty borders

**Comment by klausfilip** [comment]
weired, i cannot reproduce this.
if you put buffer_host back into ppooll.acts (what we should do anyways), does it work then?

**Comment by klausfilip** [comment]
the abstraction ll.buffer_menu did not change.
it loads buffer_host via pcontrol independent from ho_st. 
also scrolling up to your screenshot, it shows, thats it is the buffer_host inside the ppooll-package...strange, that is does not work then.

**Comment by klausfilip** [comment]
ok got it now also not working !!!!!!

**Comment by klausfilip** [comment]
yes weired! it was due to an actname-mixup when buffer_host was loaded from another act.
i delayed the loading of buffer_host (from 100ms to 300ms), but this is a dirty guess.
this loading was always deferlowed and worked for decades ;)

**Comment by klausfilip** [comment]
please test and if it works now close the issue again.

**Comment by the-steech** [comment]
this is perfect, thanks so much klaus!! :)
