### ISSUE TITLE
preferences.json

### ISSUE THREAD

**Issue by klausfilip** [ppooll-dev/ppooll#74]
i created a new branch called "presets.json" (bad name, sorry)
but this is only for you wizards to test my work, i did on some things:
- storing the ppooll-preferences as json (open prf from ho_st) (old coll is imported)
- added the "own acts folder" concept .. i called it "unshared_acts", hope you don't mind ;)
this should be intuitive as it appears at the end of the act-menu in ho_st. and will be stored in preferences
- added a "usage" concept: acts sy wants to vanish from the longish act-menu can be marked as "never" defineable with _acts_overview
this is stored in the new ppooll-preferences.json
- also there, another option to edit the favorite acts
- ignore the sometimes for now ( maybe only for sorting in act_overview)
--- remaining known issue: storing the "factory _act_overview" needs to be overworked. currently we need to reread it and edit the .json

**Comment by chausch** [comment]
from what i can see this is amazing work! 🥳

**Comment by the-steech** [comment]
Really nice klaus !!!! Didn't get to test all features but looks really slick so far

**Comment by klausfilip** [comment]
merci, this is merged into main now..

**Comment by klausfilip** [comment]
will continue seperating the factory act_overview..
