### ISSUE TITLE
matrix@ and matriarch@ output issues

### ISSUE THREAD

**Issue by Pogslammer** [ppooll-dev/ppooll#84]
I spent some time with these acts today and I had repeated issues routing the outputs for both of them. For matrix@, primarily in stereo mode, after adding a couple outputs (to delay and reverb for example), the matrix pretty quickly did not route the outputs to where they should go. Adding a third output would push it into the #2 spot (i.e., adding reverb as the third output would make it so that it was #2 in the matrix). 

I had a similar experience with matriarch@. It worked well for a time, but eventually (I think after the 5th or 6th output) multiple routings seemed broken (either going to the wrong place or nowhere at all). I hope I explained this ok, thank you for your help.

PS- I'm on latest max and ppooll code, Mac running Catalina

**Comment by the-steech** [comment]
thanks for letting us, i will take a look at this issue today!

**Comment by Pogslammer** [comment]
Great, thank you! Love my matrix routings heheh

**Comment by klausfilip** [comment]
hi @Pogslammer 
i can have a look into matrix@ but i do not get your issue clearly.
can you please give me instructions again how to reproduce the issue?

**Comment by Pogslammer** [comment]
@klausfilip I'm sorry to not be clear. I would just say to set up a flop@, prdelay@, and freeverb@ with a matrix@ in stereo mode and try routing audio from flop@ to different places. Doing so again just now, I was able to replicate the behavior (audio not going to the right act, going to two acts, etc.). Thanks so much for your help!

**Comment by klausfilip** [comment]
its working here:
![Screenshot 2023-02-15 at 16 07 40](https://user-images.githubusercontent.com/37405478/219066734-a391273e-b678-426a-9b68-50e445c54f46.png)
![Screenshot 2023-02-15 at 16 07 53](https://user-images.githubusercontent.com/37405478/219066765-0a7898ea-db43-4eaf-b6de-2aaa576152a4.png)

**Comment by klausfilip** [comment]
maybe some confusion about the outputs routing?

**Comment by Pogslammer** [comment]
@klausfilip ah my mistake, I had not been skipping a line on the output section (I assumed the number of output = matrix column). Some tidbit in the act info about that would probably help somewhat dense people such as myself.

Regarding matriarch@, there was an alternate act (matriarch2@) shared in the discord that is working and stable, so I don't need any assistance with that one. Thanks so much for everything!

**Comment by the-steech** [comment]
gonna leave this issue open so I remember to check out issue with current matriarch :)
