### ISSUE TITLE
live.ppooll screen

### ISSUE THREAD

**Issue by klausfilip** [ppooll-dev/ppooll#88]
its not enough to hide the "s" screen button in ho_st.
an environment, that has "screen 1" will just show the screen window.
we need to disable screen in live.ppooll completely.
a thought:
the js ll.live.check_envi_type is looking for @live or not, but only at loading an act.
i guess this should be a global variable at loadbang in ho_st.

**Comment by the-steech** [comment]
that's a great idea, i'm sure the global variable will come in handy.  i will work on this!

**Comment by klausfilip** [comment]
in the latest upload, there is a starting point for this. look into lload in ho_st.
also screen is disabled then in live.

**Comment by the-steech** [comment]
@klausfilip i think you beat me to fixing this... thank you :) good to close?
