### ISSUE TITLE
random@ issues

### ISSUE THREAD

**Issue by Pogslammer** [ppooll-dev/ppooll#91]
Hi there,

I am trying to use random@, and I've found that it is malfunctioning for me. It is not sending out the desired result to other acts (it doesn't seem to be sending anything at all), and it will also erase all data for each randomizer if either another randomizer is selected (alt-clicking on another number) or the number slider is changed on the far left. This is new behavior as of the last couple of days (I'm not sure what has changed, but I just now deleted all ppooll data and reinstalled Max, so it's all the freshest stuff). Thanks!

**Comment by klausfilip** [comment]
its working here.
pls give me steps to reproduce.
what is "alt-clicking on another number" ? 
why do you alt-click on which number?
...
i open random@, edit the second line after 1: with ho_st1 vol 0 0. 1.
then click on 1 in the 3rd line and see the volume in ho_st1 being randomized between 0. and 1.
...
it might very well be, that random@ is hard to understand, how to get wanted results.
pls give me instructions on what is unclear in the patch or info.

**Comment by klausfilip** [comment]
... i did a few cosmetic updates on random@ lately because i used it in the factiory-environment "ducks".
but this should not have changed its behaviour.

**Comment by Pogslammer** [comment]
Still not working for me (I have used it a bunch before this). Alt-clicking as per the info ("alt click on a number to select it without switching"). If I do anything to change the active randomizer, it erases everything I've entered, and is not sending out anything to host@ when I copy what you've done. Thanks!

**Comment by klausfilip** [comment]
do you see any errors or duplicate objects in the max-console?
if the problem persists, we only can do an online meeting to solve that.

**Comment by klausfilip** [comment]
@Pogslammer  i did some facelifting on random@. maybe it works for you now. if not lets look at it...

**Comment by Pogslammer** [comment]
Fixed! It may have been the facelift (looks great!), though I haven't used ppooll since the II.sub bug fix, so it may be that. Thanks so much for all your efforts.
